root: true                                                                      
                                                                                
env:                                                                            
  node: true                                                                    

parser: babel-eslint

parserOptions:                                                                  
  ecmaVersion: 7  
                                                                                
rules:                                                                          
  eol-last: error                                                               
  eqeqeq: [warn, allow-null]                                                   
  func-style: [2, "expression"]
  indent: [error, 4, { SwitchCase: 1 }]                                         
  no-trailing-spaces: error                                                     
  no-unused-vars: [error, { vars: all, args: none, ignoreRestSiblings: true }]  
  quotes: [2, "double", "avoid-escape"] 
  semi: [error, always]    

